### ISSUE TITLE
state `apt.update` can't run standalone

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/apt-formula#53]
I thought I'd be able to use this `apt.update` state to update the apt db on servers, so I tried

```
salt 'minion' state.sls apt.update
```

It fails with 
```
          ID: apt-get update
    Function: cmd.wait
      Result: False
     Comment: The following requisites were not found:
                                 watch:
                                     file: /etc/apt/sources.list
                                     file: /etc/apt/sources.list.d
     Started: 13:42:21.398096
    Duration: 0.061 ms
     Changes:   
```

README lists this state so it looks like it's callable standalone (not just for internal use) but it seems not.
