### ISSUE TITLE
[FEATURE] apt-daily-upgrade.timer configuration for apt.unattended

### ISSUE THREAD

**Issue by Yoda-BZH** [saltstack-formulas/apt-formula#65]
### Is your feature request related to a problem?

On debian (at least buster), the systemd service "apt-daily-upgrade.service", which install package upgrades is controlled by apt-daily-upgrade.timer.

Currently the service is triggered at 6:00 plus a random delay of 0-60 minutes :

`# cat /lib/systemd/system/apt-daily-upgrade.timer `
```
[Unit]
Description=Daily apt upgrade and clean activities
After=apt-daily.timer

[Timer]
OnCalendar=*-*-* 6:00
RandomizedDelaySec=60m
Persistent=true

[Install]
WantedBy=timers.target
```

Would it be possible to have a way of controlling the OnCalendar and RandomizedDelaySec parameters ?

Thanks

### Describe the solution you'd like

an example configuration would be :
```yaml
apt:
  unattended:
    service:
      upgrade:
        calendar: "*-*-* 6:00"
        delay: "60m"
```
